### ISSUE TITLE
Automatically include the server config object on all responses?

### ISSUE THREAD

**Issue by instanceofnull** [axisgroup/RxQAP#3]
The combined-hub examples are manually adding the server info (host) to the doc lists to allow linking to the correct server/document.  Should this be default or configurable behavior (assigning host/port/ssl/other props) to "source" property on the response from engine?

**Comment by skokenes** [comment]
covered in qix-operator branch, instead of linking server config object I went one level lower and linked to the QixClass instance that the call was made from. QixClass has the underlying session on it so you can get to server config that way. benefit of tagging the whole QixClass there is that you can trace data all the way up the stack.

Let's say you call getLayout on an object, that would return something like (pseudo)
```javascript
{ 
    source: QixClass, //-> GenericObject where it was called
    response: qLayout //-> qLayout from the server
}
```

From that source, you could keep tracing. That QixClass of type GenericObject will have a reference to it's source, which would be a QixClass of type Doc, and so on and so forth until you are back at the global.

As mentioned, all QixClass have reference to the underlying session (QixClass.session) so you can get directly to config from there.
